### ISSUE TITLE
Few troubles during data loading and query

### ISSUE THREAD

**Issue by MathiasAntunes** [CARPEM/SHRINEDocker#4]
Observation during installation at Bergonié Institute :

I noticed that placing only one of the two files pivot in data_to_import will create an error : 
`Traceback (most recent call last):
  File "/opt/dataLoader/scripts/data_pivot_transfert2.py", line 228, in <module>
	main()
  File "/opt/dataLoader/scripts/data_pivot_transfert2.py", line 224, in main
	tranfo_data(dic_db_param, dic_pivot_files)
  File "/opt/dataLoader/scripts/data_pivot_transfert2.py", line 170, in tranfo_data
	pivot = download_pivot_file(dic_db_param, dic_pivot_files)
  File "/opt/dataLoader/scripts/data_pivot_transfert2.py", line 38, in download_pivot_file
	dic_visit = visites.copy_csv_file()
  File "/opt/dataLoader/scripts/script_pivot_transfert/lect_file.py", line 23, in copy_csv_file
	f_csv = open (self.filename, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/data_to_load/OSIRIS_pivot_TumorPathologyEvent.csv'`

I imagine if i put an empty file named "OSIRIS_pivot_TumorPathologyEvent.csv" it would work but maybe put a conditional test before importing idk. Because my TumorPathologyEvent file is not complete yet (need to find a way to perform cim10 to cim-o .3).

**Comment by Parinitha-kompala** [comment]
1.There is an error while composing the docker files -"wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=a" "http://download.oracle.com/otn-pub/java/ "

2.docker-compose-dataloader.yml - is taking forever to run.
